name: CI & Deploy Backend

on:
  push:
    branches:
      - main
      - develop

env:
  REGISTRY: registry.dnp-project.ru
  IMAGE_NAME: backend

jobs:
  build-and-push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies & run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build & Push image
        run: |
          TAG=${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
          docker build \
            -f devops/Dockerfile \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG \
            .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG

  deploy:
    name: Deploy to Server
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          script: |
            TAG=${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}

            if [ "$TAG" = "latest" ]; then
              cd /opt/prod
            else
              cd /opt/stage
            fi

            docker compose pull backend
            docker compose up -d backend
